# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# .travis.yml

# from tigris

# from Andy South (rnaturalearth's travis.yml to build sf)
language: r
warnings_are_errors: true
sudo: required
cache: packages

env:
        global:
                - MAKE_FLAGS="-j 2"
                - _R_CHECK_FORCE_SUGGESTS=0

matrix:
        include:
                - os: linux
                  r: release
                  dist: trusty # 14.04
                  env: R_CODECOV=true
                - os: linux
                  r: devel
                  dist: trusty
                  env: _R_CHECK_LENGTH_1_CONDITION_=package:_R_CHECK_PACKAGE_NAME_,abort,verbose

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - devtools

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
      - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

r_check_args: "--as-cran --run-donttest"
