# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# .travis.yml

language: r
warnings_are_errors: true
r_check_args: --as-cran --run-donttest
sudo: required
cache: packages

env:
        global:
                - MAKE_FLAGS="-j 2"
                - _R_CHECK_FORCE_SUGGESTS=0

matrix:
        include:
                - os: linux
                  r: release
                  dist: trusty # 14.04
                  env: R_CODECOV=true
                - os: linux
                  r: devel
                  dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"
  - Rscript -e "devtools::install_github('jimhester/covr')"

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
